// <auto-generated />
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DAL.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20180124113807_FirtConnection")]
    partial class FirtConnection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DAL.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Car");

                    b.Property<string>("Classe")
                        .IsRequired();

                    b.Property<int>("Cons");

                    b.Property<int>("Des");

                    b.Property<int>("For");

                    b.Property<int>("Int");

                    b.Property<int>("Sab");

                    b.Property<int>("Xp");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("DAL.Model.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PlayerId");

                    b.Property<string>("nome")
                        .IsRequired();

                    b.Property<string>("tipo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("DAL.Model.Skill", b =>
                {
                    b.HasOne("DAL.Model.Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
